# Nixpacks configuration for subfolder structure
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r nexero-backend/requirements.txt"]

[start]
cmd = "cd nexero-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
