[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
    "cd nexero-backend",
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "cd nexero-backend && . /opt/venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
