# Railway Configuration
# https://docs.railway.app/deploy/deployments

[build]
builder = "NIXPACKS"
buildCommand = "cd nexero-backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd nexero-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
